---
downloads: ~/.ansible-downloads/

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# Set to 'true' to install dotfiles
configure_dotfiles: true
dotfiles_repo: https://github.com/bartdorlandt/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/git/dotfiles
dotfiles_repo_version: master
dotfiles_files:
  - .screenrc
  # - .shell_aliases
  - .tmux.conf
  - .vimrc
  - .vimrc.bundles
  # - .zshrc
  # - .zprofile
  - .pythonstartup

# Glob pattern to ansible task files to run after all other tasks are finished.
# post_provision_tasks: "{{ playbook_dir }}/../tasks/*.yml"

# Pyenv config
# Desired Python versions
pyenv_python39_version: "3.9.18"
pyenv_python310_version: "3.10.13"
pyenv_python311_version: "3.11.8"
pyenv_python312_version: "3.12.2"

# Python versions to install
pyenv_python_versions:
  - "{{ pyenv_python39_version }}"
  - "{{ pyenv_python310_version }}"
  - "{{ pyenv_python311_version }}"
  - "{{ pyenv_python312_version }}"

# Set global pyenv version
pyenv_global: "{{ pyenv_python311_version }}"
pip_executable: "{{ ansible_env.HOME }}/.pyenv/shims/pip3"

pip_packages:
  - name: ansible
    state: latest
  - name: ansible-lint
    state: latest
  - name: pip
    state: latest

#git_repos:
#  # Make sure the SSH key have been loaded to bitbucket and github
#  # when options: MacOSX, Ubuntu, always
#  - {repo: $url, path: ~/git/<path>}

git_init_default_branch: master
git_pull_rebase: true

# ohmyzsh_plugins: "git zsh-autosuggestions zsh-syntax-highlighting tmux poetry"
# ohmyzsh_plugins: "git macos zsh-autosuggestions zsh-syntax-highlighting"

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - "App Store"
  - Calendar
  - Contacts
  - FaceTime
  - Keynote
  - Launchpad
  - Mail
  - Maps
  - Music
  - News
  - Numbers
  - Pages
  - Photos
  - Podcasts
  - Safari
  - TV

dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 1
  - name: "Reminders"
    path: "/System/Applications/Reminders.app"
    pos: 2
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 3
  - name: "Notes"
    path: "/System/Applications/Notes.app/"
    pos: 4
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 5
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 6
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 7
  - name: "PyCharm CE"
    path: "/Applications/PyCharm CE.app"
    pos: 8
  - name: "Notion"
    path: "/Applications/Notion.app/"
    pos: 9
  - name: "Authy Desktop"
    path: "/Applications/Authy Desktop.app/"
    pos: 10
  - name: "WhatsApp"
    path: "/Applications/WhatsApp.app/"
    pos: 11
  - name: "Signal"
    path: "/Applications/Signal.app/"
    pos: 12
  - name: "Beeper"
    path: "/Applications/Beeper.app/"
    pos: 13
  - name: "Messages"
    path: "/System/Applications/Messages.app"
    pos: 14
  - name: "System Settings"
    path: "/System/Applications/System Settings.app/"
    pos: 15
  - name: "Bitwarden"
    path: "/Applications/Bitwarden.app/"
    pos: 16

homebrew_installed_packages:
  - bat
  - coreutils
  - docker
  - dockutil
  - eza
  - fd
  - fish
  - fzf
  - gh
  - git
  - gnupg
  - go
  - gping
  - htop
  - httpie
  - iproute2mac
  - just
  - jq
  - mtr
  - openssh
  - poetry
  - prettyping
  - pwgen
  - ripgrep
  - starship
  - telnet
  - tmate
  - tmux
  - tree
  - wget
  - whois
  - xping
  - yq
  - zoxide

homebrew_not_install_packages: []
homebrew_extra_install_packages: []

homebrew_taps:
  - martintopholm/xping

homebrew_cask_accept_external_apps: true
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - authy
  - clipy
  - devtoys
  - docker
  - drawio
  - dropbox
  - elgato-camera-hub
  - elgato-stream-deck
  - elgato-control-center
  - espanso
  - firefox
  - github
  - google-chrome
  - google-drive
  - hiddenbar
  - iterm2
  - karabiner-elements
  - keepassx
  - logi-options-plus
  - notion
  - postman
  - pycharm-ce
  - shortcat
  - signal
  - slack
  - sublime-text
  - synology-drive
  - tailscale
  - telegram
  - uv
  - visual-studio-code
  - wireshark
  - yubico-yubikey-manager
  - zoom

homebrew_not_install_cask_apps: []
homebrew_extra_install_cask_apps: []

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 409203825, name: "Numbers" }
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 1475387142, name: "Tailscale" }

# mas_uninstalled_apps:
#   - { id: 408981434, name: "iMovie" }
#   - { id: 682658836, name: "GarageBand" }
mas_email: ""
mas_password: ""

# Set to 'true' to configure osx defaults
configure_osx: false
osx_script: "~/.osx --no-restart"

user_group: staff

sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"

fish_omf_plugins:
  - bass
  - bang-bang
