---
downloads: ~/.ansible-downloads/

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# Set to 'true' to install dotfiles
configure_dotfiles: true
dotfiles_repo: https://github.com/bartdorlandt/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/git/dotfiles
dotfiles_repo_version: master
dotfiles_files:
  - .screenrc
  - .shell_aliases
  - .tmux.conf
  - .vimrc
  - .vimrc.bundles
  - .zshrc

# Glob pattern to ansible task files to run after all other tasks are finished.
# post_provision_tasks: "{{ playbook_dir }}/../tasks/*.yml"

# Pyenv config
# # Latest Python versions
# pyenv_python38_version: "3.8.13"
#  pyenv_python39_version: "3.9.16"
pyenv_python310_version: "3.10.10"
pyenv_python311_version: "3.11.2"

# Python versions to install
pyenv_python_versions:
  # - "{{ pyenv_python38_version }}"
  # - "{{ pyenv_python39_version }}"
  - "{{ pyenv_python310_version }}"
  - "{{ pyenv_python311_version }}"

# Set global pyenv version
pyenv_global: "{{ pyenv_python310_version }}"
pip_executable: "{{ ansible_env.HOME }}/.pyenv/versions/{{ pyenv_global }}/bin/pip3"

pip_packages:
  - name: ansible
    state: latest
  - name: ansible-lint
    state: latest
  - name: pip
    state: latest

#git_repos:
#  # Make sure the SSH key have been loaded to bitbucket and github
#  # when options: MacOSX, Ubuntu, always
#  - {repo: $url, path: ~/git/<path>}

git_init_default_branch: master
git_pull_rebase: false

# ohmyzsh_plugins: "git zsh-autosuggestions zsh-syntax-highlighting tmux poetry"
ohmyzsh_plugins: "git zsh-autosuggestions zsh-syntax-highlighting"

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - "App Store"
  - Calendar
  - Contacts
  - FaceTime
  - Keynote
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Numbers
  - Pages
  - Photos
  - Podcasts
  - Safari
  - TV

dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 1
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 2
  - name: "Notes"
    path: "/System/Applications/Notes.app/"
    pos: 3
  - name: "Reminders"
    path: "/System/Applications/Reminders.app/"
    pos: 4
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 6
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 8
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 9
  - name: "PyCharm CE"
    path: "/Applications/PyCharm CE.app"
    pos: 10
  - name: "Notion"
    path: "/Applications/Notion.app/"
    pos: 11
  - name: "Authy Desktop"
    path: "/Applications/Authy Desktop.app/"
    pos: 12
  - name: "WhatsApp"
    path: "/Applications/WhatsApp.app/"
    pos: 13
  - name: "Signal"
    path: "/Applications/Signal.app/"
    pos: 14
  - name: "Telegram"
    path: "/Applications/Telegram.app/"
    pos: 15
  - name: "System Settings"
    path: "/System/Applications/System Settings.app/"
    pos: 16
  - name: "Bitwarden"
    path: "/Applications/Bitwarden.app/"
    pos: 17

homebrew_installed_packages:
  - bat
  - coreutils
  - docker
  - fd
  - fzf
  - gh
  - git
  - gnupg
  - go
  - htop
  - httpie
  - iproute2mac
  - jq
  - mtr
  - openssh
  - poetry
  - prettyping
  - pwgen
  - ripgrep
  - starship
  - tailscale
  - telnet
  - tmate
  - tmux
  - tree
  - wget
  - whois
  - xping

homebrew_taps:
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/core
  - martintopholm/xping

homebrew_cask_accept_external_apps: true
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - authy
  - bitwarden
  - clipy
  - docker
  - dockutil
  - drawio
  - dropbox
  - firefox
  - github
  - google-chrome
  - google-drive
  - iterm2
  - karabiner-elements
  - keepassx
  - logi-options-plus
  - notion
  - rectangle
  - pycharm-ce
  - signal
  - slack
  - sublime-text
  - telegram
  - virtualbox
  - visual-studio-code
  - whatsapp
  - wireshark
  - yubico-yubikey-manager
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 409203825, name: "Numbers" }
# mas_uninstalled_apps:
#   - { id: 408981434, name: "iMovie" }
#   - { id: 682658836, name: "GarageBand" }
mas_email: ""
mas_password: ""

# Set to 'true' to configure osx defaults
configure_osx: false
osx_script: "~/.osx --no-restart"

user_group: staff

sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
