---
- name: Laptop setup playbook
  hosts: all
  connection: local

  environment:
    PATH: /opt/homebrew/bin:/opt/homebrew/sbin:{{ ansible_env.PATH }}

  pre_tasks:
    - name: Fail if the VIRTUAL_ENV variable is not defined
      ansible.builtin.debug:
        msg: "VIRTUAL_ENV: {{ lookup('ansible.builtin.env', 'VIRTUAL_ENV') }}"
      failed_when: lookup('ansible.builtin.env', 'VIRTUAL_ENV') == ""

    - name: Include config.yml variables
      ansible.builtin.include_vars: config.yml
      tags: always
    - name: Include .env.yml variables
      ansible.builtin.include_vars: .env.yml
      tags: always
    - name: Remove unwanted homebrew packages/cask from variable
      ansible.builtin.set_fact:
        homebrew_installed_packages: "{{ homebrew_installed_packages | difference(homebrew_not_install_packages) }} "
        homebrew_cask_apps: "{{ homebrew_cask_apps | difference(homebrew_not_install_cask_apps) }} "
      tags: always
    - name: Add extra homebrew packages/cask to variable
      ansible.builtin.set_fact:
        homebrew_installed_packages: "{{ homebrew_installed_packages | difference(homebrew_extra_install_packages) }} "
        homebrew_cask_apps: "{{ homebrew_cask_apps | difference(homebrew_extra_install_cask_apps) }} "
      tags: always

  tasks:
    - name: Git setup
      ansible.builtin.import_tasks: tasks/git-setup.yml
      tags: git
    - name: Include the homebrew role
      ansible.builtin.include_role:
        name: geerlingguy.mac.homebrew
        apply:
          tags:
            - homebrew
      tags: homebrew

    - name: Other MAC software
      ansible.builtin.include_role:
        name: geerlingguy.mac.mas
        apply:
          tags:
            - mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: mas
    - name: Setup the dock
      ansible.builtin.include_role:
        name: geerlingguy.mac.dock
        apply:
          tags:
            - dock
      when: configure_dock
      tags: dock
    - name: OSX defaults
      ansible.builtin.include_role:
        name: osx_defaults
        apply:
          tags:
            - osx_defaults
      tags: osx_defaults
    - name: App iClouddrive
      ansible.builtin.import_tasks: tasks/iclouddrive.mac.yml
      tags: iclouddrive
    - name: App iTerm2
      ansible.builtin.import_tasks: tasks/iterm2.mac.yml
      tags: iterm2
    - name: App karabiner
      ansible.builtin.import_tasks: tasks/karabiner.mac.yml
      tags: karabiner
    - name: Sudo touchID
      ansible.builtin.import_tasks: tasks/sudo_touchid.mac.yml
      tags: touchid

    # System independent tasks
    - name: Set up dirs and files
      ansible.builtin.import_tasks: tasks/forward.yml
      tags: filemod

    - name: Dotfiles
      ansible.builtin.include_role:
        name: geerlingguy.dotfiles
        apply:
          tags:
            - dotfiles
      tags: dotfiles
      when: configure_dotfiles

    - name: Import task - ssh
      ansible.builtin.import_tasks: tasks/ssh.yml
      tags: ssh
    - name: Import task - vimVundle
      ansible.builtin.import_tasks: tasks/vimVundle.yml
      tags: vim
    - name: Import task - git-repos
      ansible.builtin.import_tasks: tasks/git-repos.yml
      tags: git-repos
    - name: Import task - python
      ansible.builtin.import_tasks: tasks/python.yml
      tags: python
    - name: Shell prompt
      ansible.builtin.include_role:
        name: shell_prompt
        apply:
          tags:
            - shell_prompt
      tags: shell_prompt
    - name: Espanso
      ansible.builtin.include_role:
        name: bartdorlandt.espanso
        apply:
          tags:
            - espanso
      tags: espanso
    - name: Poetry
      ansible.builtin.include_role:
        name: bartdorlandt.poetry
        apply:
          tags:
            - poetry
      vars:
        poetry_ohmyzsh_plugin: false
        virtualenvs_in_project: true
      tags: poetry
    - name: Fzf
      ansible.builtin.include_role:
        name: bartdorlandt.fzf
        apply:
          tags:
            - fzf
      tags: fzf
    - name: Import task - sublimetext
      ansible.builtin.import_tasks: tasks/sublime-text.yml
      tags: sublimetext
    - name: Import task - dynv6
      ansible.builtin.import_tasks: tasks/dynv6.yml
      tags: dynv6
      when: ddns.dynv6_token is defined and ddns.dynv6_name is defined
    - name: Import task - symlinks
      ansible.builtin.import_tasks: tasks/symlinks.yml
      tags: symlinks
    - name: Include the fish role
      ansible.builtin.include_role:
        name: fish
        apply:
          tags:
            - fish
      tags: fish
