[project]
name = "macbook-playbook"
version = "0.2.0"
description = "Enable dependencies for a new Macbook"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["ansible-lint>=6.8.7", "ansible>=11.0.0"]
