---
roles:
  - name: geerlingguy.dotfiles
  - name: geerlingguy.docker
  - name: bartdorlandt.espanso
  - name: bartdorlandt.fzf
  - name: bartdorlandt.ohmyzsh
  - name: bartdorlandt.poetry
  - name: elliotweiser.osx-command-line-tools

collections:
  - name: geerlingguy.mac
