version: "3"

# Run any command with additional parameters behind the '--'
# task playbook -- -C

tasks:
  default:
    silent: true
    cmd: task -l --sort none

  playbook:
    desc: "Run the main playbook, with -K"
    aliases: [all]
    cmds:
      - uv run ansible-playbook main.yml -K {{.CLI_ARGS}}
    preconditions:
      - test -f .env.yml

  playbook:homebrew:
    desc: "Update/clean the homebrew packages"
    cmds:
      - uv run ansible-playbook main.yml -K --tags=homebrew {{.CLI_ARGS}}
    preconditions:
      - test -f .env.yml

  list-tags:
    desc: "List available tags in the playbook"
    cmds:
      - uv run ansible-playbook main.yml --list-tags

  tags:
    desc: 'Run the playbook with provided tags: ''task TAGS="tag1,tag2" tags'''
    cmds:
      - task: playbook
        vars:
          CLI_ARGS: --tags={{.TAGS}} {{.CLI_ARGS}}
    requires:
      vars:
        - TAGS

  step:
    desc: "Run the playbook with --step"
    cmds:
      - task: playbook
        vars:
          CLI_ARGS: --step {{.CLI_ARGS}}

  install:all:
    desc: Install all dependencies
    aliases: [install]
    deps:
      - install:uv
      - install:xcode
    cmds:
      - task: install:repo

  install:uv:
    desc: Sync uv
    cmds:
      - uv sync

  install:xcode:
    set: [pipefail]
    run: once
    desc: Install Xcode
    cmds:
      - |
        xcode-select -p &>/dev/null || xcode-select --install
        if [ "`xcode-select -p`" != "/Library/Developer/CommandLineTools" ]; then sudo xcode-select -switch /Library/Developer/CommandLineTools; fi

  install:repo:
    desc: Install repo dependencies (ansible and git_submodules)
    deps: [install:ansible:requirements:force, install:git:submodules]

  install:ansible:requirements:
    desc: Install the ansible requirements
    cmd: uv run ansible-galaxy install -r requirements.yml {{.CLI_ARGS}}

  install:ansible:requirements:force:
    desc: Force install the ansible requirements
    cmds:
      - task: install:ansible:requirements
        vars:
          CLI_ARGS: --force

  install:git:submodules:
    desc: Install the git submodules
    cmd: git submodule update --init --recursive

  clean:
    desc: Erase the directories
    prompt: Are you sure?
    cmds:
      - rm -rf ./roles/geerlingguy.*
      - rm -rf ./roles/bartdorlandt.*
      - rm -rf ./roles/monolithprojects.homebrew
      - rm -rf ./roles/elliotweiser.osx-command-line-tools
