---
- name: Create a forward file # noqa template-instead-of-copy
  ansible.builtin.copy:
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    mode: "0600"
    dest: "{{ ansible_env.HOME }}/.forward"
    content: |
      {{ email }}
