---
- name: Create user file for Git config
  ansible.builtin.template:
    src: gitconfig_user.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: "0600"
  when: configure_dotfiles

- name: Make sure git directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "750"
  loop: "{{ git_dirs }}"

- name: Make sure .config/git directorie exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/git"
    state: directory
    mode: "750"

- name: Link global git ignore file
  ansible.builtin.file:
    src: "{{ playbook_dir }}/tasks/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/git/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    state: link
  loop:
    - gitignore
