---
- name: Link iCloud drive into home folder.
  ansible.builtin.file:
    dest: "~/iCloudDrive"
    src: "~/Library/Mobile Documents/com~apple~CloudDocs/"
    state: link
    force: true
  become: false
