---
- name: Add VScode
  become: true
  block:
    - name: Download VScode asc key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/trusted.gpg.d/vscode.asc
        mode: "0644"

    - name: Apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/vscode.asc] https://packages.microsoft.com/repos/code stable main"
        state: present
        mode: "0644"

    - name: Add code to packages
      ansible.builtin.set_fact:
        packages: "{{ packages + ['code'] }}"
