- name: Create the direnv plugins configuration file
  when: direnv_plugins_path is defined and direnv_plugins_path != ""
  block:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: "{{ direnv_plugins_path | dirname }}"
        state: directory
        mode: "0755"
    - name: Ensure the file exists
      ansible.builtin.file:
        path: "{{ direnv_plugins_path }}"
        state: touch
        mode: "0600"
        modification_time: preserve
        access_time: preserve

    - name: Fill the file with the direnv configuration
      ansible.builtin.blockinfile:
        path: "{{ direnv_plugins_path }}"
        block: |
          {{ direnv_plugins_config }}
