---
- name: Oh-my-ZSH-role
  ansible.builtin.include_role:
    name: bartdorlandt.ohmyzsh
    apply:
      tags:
        - ohmyzsh
  tags: ohmyzsh

# starship
- name: Create the starship.toml
#  when: ohmyzsh_plugins is defined
  block:
    - name: Ensure the ~/.config/starship.toml file exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/starship.toml"
        state: touch
        mode: 0600
        modification_time: preserve
        access_time: preserve

    - name: Fill the starship.toml
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.config/starship.toml"
        block: |
          {{ starship_config }}
